# Generated by Django 3.0.6 on 2021-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создана')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыть')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Приоритет')),
            ],
        ),
    ]
