# Generated by Django 3.0.6 on 2021-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('desctiption', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
